apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: im-nfs
  namespace: im
  labels:
    app: im-nfs
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: hw-nfs-storage
  resources:
    requests:
      storage: "10Gi"